### ISSUE TITLE
Collex spidering can't retrieve full text

### ISSUE THREAD

**Issue by cwulfman** [cwulfman/bluemountainsprings#1]
When Collex tries to exercise the constituent spring to get indexable text, it gets an empty result even though the response code is 200.

It turns out this is an issue on the eXist-db side; restxq isn't handling (some?) requests that lack Accept headers.

The work-around, for now, is to include the indexable text in the Collex RDF instead of linking to it.

**Comment by cwulfman** [comment]
On Jan 19, 2017, at 5:30 PM, nikolaus wasmoen <nlwasmoe@buffalo.edu> wrote:

Hi Cliff, 

I've debugged and tested the sample you sent, which you can now see on the testing site: http://edge.modnets.org/search?a=bmtn_bmtnaap. Note that I removed the other RDF for Broom on the testing site for clarity's sake, so only the sample issue RDF is there right now (34 items). 

The full text as you've entered it in the RDF appears to be working, e.g. a search for "run true" (without quotes) returns the expected results: http://edge.modnets.org/search?a=bmtn_bmtnaap&q=run%20true. 

There was a missing value for role:CRE in one object (http://bluemountain.princeton.edu/exist/restxq/springs/constituent/bmtnaap_1921-11_01/c043), which I just changed to "Unknown" to get it to work.  

One issue: the rdfs:seeAlso @rdf:resource values do not appear to be working links to the respective issues on the Blue Mountain site. It looks like the "issueURN" is needed instead/in addition to the given "issueid" field:

e.g. 

<rdfs:seeAlso @rdf:resource="http://bluemountain.princeton.edu/exist/apps/bluemountain/issue.html?issueid=bmtnaap_1921-11_01"/>

Should be changed to: 

<rdfs:seeAlso @rdf:resource="http://bluemountain.princeton.edu/exist/apps/bluemountain/issue.html?issueURN=bmtnaap_1921-11_01"/>

**Comment by modnets** [comment]
Hi Cliff, 

I accessed the updated test fulltext RDF via:  

curl -H'Accept:application/rdf+xml' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap_1921-11_01 

After debugging, the @rdf:resource URLs appear to be working correctly and linking to the right page on the BM site.  You can review these entries on ModNets' testing site: http://edge.modnets.org/search?a=bmtn_bmtnaap. 

Please check these entries on the testing site. If they appear OK, then you can go ahead and begin full RDF regeneration. 

Best wishes, 
Nick

**Comment by cwulfman** [comment]
Nick Wasmoen wrote:

> I went ahead and debugged all the BMTN RDF you sent (with the omissions described in my last email). The debugger caught two global bugs and 93 local bugs (mostly missing dc:title elements). Below are the global issues, and attached you'll find a log of the local issues that came up. 
>
>1. For all objects with <collex:genre>Unspecified</collex:genre>, this element is repeated twice. The duplicate <collex:genre>Unspecified</collex:genre> elements should be removed.
>
>2.  All the title-level collection objects include a <collex:text> element, which should be removed. The title-level objects do not need this element, since the full text is accessed via the article-level objects. 

>e.g. In bmtnaab_1920-02_01.rdf, on line 13, delete <collex:text rdf:resource="http://bluemountain.princeton.edu/exist/restxq/springs/text/bmtnaab_1920-02_01"/>
